### ISSUE TITLE
sys api crashing after shitty update xD

### ISSUE THREAD

**Issue by FundyJo** [Krillsson/sys-API#150]
2024-07-14 11:21:39 
2024-07-14 11:21:39 
2024-07-14 11:21:39   ______ ______ ______ ______ ______ ______ ______
2024-07-14 11:21:39  |______|______|______|______|______|______|______|
2024-07-14 11:21:39  | |                                            | |
2024-07-14 11:21:39  | |    / ____|         | |                     | |
2024-07-14 11:21:39  | |   | (___  _   _ ___| |_ ___ _ __ ___       | |
2024-07-14 11:21:39  | |    \___ \| | | / __| __/ _ | '_ ` _ \      | |
2024-07-14 11:21:39  | |    ____) | |_| \__ | ||  __| | | | | |     | |
2024-07-14 11:21:39  | |   |_____/ \__, |___/\__\___|_| |_| |_|     | |
2024-07-14 11:21:39  | |            __/ |                           | |
2024-07-14 11:21:39  |_|           |___/__ _____                    |_|
2024-07-14 11:21:39  | |       /\   |  __ |_   _|                   | |
2024-07-14 11:21:39  | |      /  \  | |__) || |                     | |
2024-07-14 11:21:39  | |     / /\ \ |  ___/ | |                     | |
2024-07-14 11:21:39  | |    / ____ \| |    _| |_                    | |
2024-07-14 11:21:39  | |   /_/    \_|_|   |_____|                   | |
2024-07-14 11:21:39  | |                                            | |
2024-07-14 11:21:39  |_|____ ______ ______ ______ ______ ______ ____|_|
2024-07-14 11:21:39  |______|______|______|______|______|______|______|
2024-07-14 11:21:39 
2024-07-14 11:21:39 
2024-07-14 11:21:39 2024-07-14T09:21:39.221Z  INFO 1 --- [sysapi] [           main] c.krillsson.sysapi.SysAPIApplicationKt   : Starting AOT-processed SysAPIApplicationKt v0.31.2 using Java 21.0.2 with PID 1 (/app/sysapi started by root in /)
2024-07-14 11:21:39 2024-07-14T09:21:39.221Z  INFO 1 --- [sysapi] [           main] c.krillsson.sysapi.SysAPIApplicationKt   : No active profile set, falling back to 1 default profile: "default"
2024-07-14 11:21:39 2024-07-14T09:21:39.261Z  WARN 1 --- [sysapi] [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server
2024-07-14 11:21:39 2024-07-14T09:21:39.262Z ERROR 1 --- [sysapi] [           main] o.s.boot.SpringApplication               : Application run failed
2024-07-14 11:21:39 
2024-07-14 11:21:39 org.springframework.context.ApplicationContextException: Unable to start web server
2024-07-14 11:21:39     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:618) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at com.krillsson.sysapi.SysAPIApplicationKt.main(SysAPIApplication.kt:66) ~[sysapi:0.31.2]
2024-07-14 11:21:39     at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH) ~[na:na]
2024-07-14 11:21:39 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory': Error creating bean with name 'tomcatSslStoreCustomizer': Unsatisfied dependency expressed through method 'tomcatSslStoreCustomizer' parameter 1: Error creating bean with name 'certificateNamesCreator': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'networkMetrics': Unsatisfied dependency expressed through method 'networkMetrics' parameter 0: Error creating bean with name 'metrics': Unsatisfied dependency expressed through method 'metrics' parameter 0: Error creating bean with name 'userConfigFile': Instantiation of supplied bean failed
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:607) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:223) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:186) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     ... 9 common frames omitted
2024-07-14 11:21:39 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tomcatSslStoreCustomizer': Unsatisfied dependency expressed through method 'tomcatSslStoreCustomizer' parameter 1: Error creating bean with name 'certificateNamesCreator': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'networkMetrics': Unsatisfied dependency expressed through method 'networkMetrics' parameter 0: Error creating bean with name 'metrics': Unsatisfied dependency expressed through method 'metrics' parameter 0: Error creating bean with name 'userConfigFile': Instantiation of supplied bean failed
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:344) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:264) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:204) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1217) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:665) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getWebServerFactoryCustomizerBeans(WebServerFactoryCustomizerBeanPostProcessor.java:87) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getCustomizers(WebServerFactoryCustomizerBeanPostProcessor.java:78) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:70) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58) ~[sysapi:3.3.0-M3]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[sysapi:6.1.5]
2024-07-14 11:21:39     ... 17 common frames omitted
2024-07-14 11:21:39 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'certificateNamesCreator': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'networkMetrics': Unsatisfied dependency expressed through method 'networkMetrics' parameter 0: Error creating bean with name 'metrics': Unsatisfied dependency expressed through method 'metrics' parameter 0: Error creating bean with name 'userConfigFile': Instantiation of supplied bean failed
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:344) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:264) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:204) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1217) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:229) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:341) ~[na:na]
2024-07-14 11:21:39     ... 36 common frames omitted
2024-07-14 11:21:39 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'networkMetrics': Unsatisfied dependency expressed through method 'networkMetrics' parameter 0: Error creating bean with name 'metrics': Unsatisfied dependency expressed through method 'metrics' parameter 0: Error creating bean with name 'userConfigFile': Instantiation of supplied bean failed
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:344) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:264) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:204) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1217) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:229) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:341) ~[na:na]
2024-07-14 11:21:39     ... 53 common frames omitted
2024-07-14 11:21:39 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'metrics': Unsatisfied dependency expressed through method 'metrics' parameter 0: Error creating bean with name 'userConfigFile': Instantiation of supplied bean failed
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:344) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:264) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:204) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1217) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:229) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:341) ~[na:na]
2024-07-14 11:21:39     ... 70 common frames omitted
2024-07-14 11:21:39 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userConfigFile': Instantiation of supplied bean failed
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1223) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:229) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:341) ~[na:na]
2024-07-14 11:21:39     ... 87 common frames omitted
2024-07-14 11:21:39 Caused by: java.lang.IllegalStateException: Config file is missing at /config/configuration.yml
2024-07-14 11:21:39     at com.krillsson.sysapi.SysApiConfiguration.userConfigFile(SysApiConfiguration.kt:62) ~[sysapi:0.31.2]
2024-07-14 11:21:39     at com.krillsson.sysapi.SysApiConfiguration$$SpringCGLIB$$0.CGLIB$userConfigFile$10(<generated>) ~[sysapi:0.31.2]
2024-07-14 11:21:39     at com.krillsson.sysapi.SysApiConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[sysapi:0.31.2]
2024-07-14 11:21:39     at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[na:na]
2024-07-14 11:21:39     at com.krillsson.sysapi.SysApiConfiguration$$SpringCGLIB$$0.userConfigFile(<generated>) ~[sysapi:0.31.2]
2024-07-14 11:21:39     at com.krillsson.sysapi.SysApiConfiguration__BeanDefinitions.lambda$getUserConfigFileInstanceSupplier$0(SysApiConfiguration__BeanDefinitions.java:51) ~[na:na]
2024-07-14 11:21:39     at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:63) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:51) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$withGenerator$0(BeanInstanceSupplier.java:171) ~[na:na]
2024-07-14 11:21:39     at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:206) ~[na:na]
2024-07-14 11:21:39     at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:218) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:206) ~[na:na]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949) ~[sysapi:6.1.5]
2024-07-14 11:21:39     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1217) ~[sysapi:6.1.5]
2024-07-14 11:21:39     ... 100 common frames omitted
2024-07-14 11:21:39

**Comment by Krillsson** [comment]
Are you running the native build? Try with the latest image I pushed to `krillsson/sys-api:native` 5 min ago

**Comment by FundyJo** [comment]
Thanks

Christian ***@***.***> schrieb am So., 14. Juli 2024, 19:23:
