### ISSUE TITLE
spits out a bunch of errors whenever i try to see my status

### ISSUE THREAD

**Issue by colebolebole** [Krillsson/sys-API#155]
![Screenshot_20240913-222043](https://github.com/user-attachments/assets/d53f2472-2c69-44de-b152-af56119cee7c)

Error:

---

2024-09-13T22:17:59.807-04:00 ERROR 18244 --- [sysapi] [nio-8443-exec-2] s.g.e.ExceptionResolversExceptionHandler : Unresolved IllegalArgumentException for executionId 4d40b8fa-c966-a357-9560-ef8d3a9432a4

java.lang.IllegalArgumentException: MonitorManager requires initialization. Call initialize
        at com.krillsson.sysapi.core.metrics.windows.OHMManager.initializedMonitorManager(OHMManager.kt:107) ~[sysapi-0.31.3-all.jar:0.31.3]
        at com.krillsson.sysapi.core.metrics.windows.OHMManager.update(OHMManager.kt:103) ~[sysapi-0.31.3-all.jar:0.31.3]
        at com.krillsson.sysapi.core.metrics.windows.WindowsCpuMetrics$WindowsCpuSensors.cpuHealth(WindowsCpuMetrics.kt:23) ~[sysapi-0.31.3-all.jar:0.31.3]
        at com.krillsson.sysapi.core.metrics.defaultimpl.DefaultCpuMetrics.cpuLoad(DefaultCpuMetrics.kt:49) ~[sysapi-0.31.3-all.jar:0.31.3]
        at com.krillsson.sysapi.graphql.ProcessorResolver.metrics(ProcessorResolver.kt:13) ~[sysapi-0.31.3-all.jar:0.31.3]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
        at org.springframework.graphql.data.method.InvocableHandlerMethodSupport.doInvoke(InvocableHandlerMethodSupport.java:117) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.data.method.annotation.support.DataFetcherHandlerMethod.validateAndInvoke(DataFetcherHandlerMethod.java:155) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.data.method.annotation.support.DataFetcherHandlerMethod.invoke(DataFetcherHandlerMethod.java:126) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.data.method.annotation.support.DataFetcherHandlerMethod.invoke(DataFetcherHandlerMethod.java:105) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.data.method.annotation.support.AnnotatedControllerConfigurer$SchemaMappingDataFetcher.get(AnnotatedControllerConfigurer.java:522) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.execution.ContextDataFetcherDecorator.lambda$get$0(ContextDataFetcherDecorator.java:85) ~[sysapi-0.31.3-all.jar:0.31.3]
        at io.micrometer.context.ContextSnapshot.lambda$wrap$1(ContextSnapshot.java:106) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.execution.ContextDataFetcherDecorator.get(ContextDataFetcherDecorator.java:85) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:329) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:305) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:243) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:214) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:63) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:729) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:502) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:453) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:216) ~[sysapi-0.31.3-all.jar:0.31.3]
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200) ~[na:na]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:215) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:63) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:729) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:502) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:453) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:216) ~[sysapi-0.31.3-all.jar:0.31.3]
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200) ~[na:na]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:215) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:63) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.Execution.executeOperation(Execution.java:162) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.execution.Execution.execute(Execution.java:104) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.GraphQL.execute(GraphQL.java:568) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.GraphQL.lambda$parseValidateAndExecute$13(GraphQL.java:487) ~[sysapi-0.31.3-all.jar:0.31.3]
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341) ~[na:na]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482) ~[sysapi-0.31.3-all.jar:0.31.3]
        at graphql.GraphQL.lambda$executeAsync$9(GraphQL.java:440) ~[sysapi-0.31.3-all.jar:0.31.3]
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341) ~[na:na]
        at graphql.GraphQL.executeAsync(GraphQL.java:428) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.execution.DefaultExecutionGraphQlService.lambda$execute$2(DefaultExecutionGraphQlService.java:110) ~[sysapi-0.31.3-all.jar:0.31.3]
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:47) ~[sysapi-0.31.3-all.jar:0.31.3]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[sysapi-0.31.3-all.jar:0.31.3]
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4634) ~[sysapi-0.31.3-all.jar:0.31.3]
        at reactor.core.publisher.Mono.toFuture(Mono.java:5146) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.server.webmvc.GraphQlHttpHandler.prepareResponse(GraphQlHttpHandler.java:82) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.graphql.server.webmvc.AbstractGraphQlHttpHandler.handleRequest(AbstractGraphQlHttpHandler.java:132) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.servlet.function.support.HandlerFunctionAdapter.handle(HandlerFunctionAdapter.java:108) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[sysapi-0.31.3-all.jar:0.31.3]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[sysapi-0.31.3-all.jar:0.31.3]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:213) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[sysapi-0.31.3-all.jar:0.31.3]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[sysapi-0.31.3-all.jar:0.31.3]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[na:na]

**Comment by colebolebole** [comment]
i didnt run it as admin, i get another error basically stating it cant find the path specified when i do

**Comment by Krillsson** [comment]
Can you try setting this to false in the configuration.yml

  enableOhmJniWrapper: false

And I will have a deeper look when I have an opportunity.

Would also appreciate the error you get when you run it as administrator

**Comment by colebolebole** [comment]
Thank you, it worked! only thing wrong now is cpu temps are at 0c, provided is the error when i run it as admin
-
![cmd_mVgAO5XSiv](https://github.com/user-attachments/assets/ed09aea1-85ef-410e-8642-c29b9b3c304c)

**Comment by Krillsson** [comment]
Awesome that it worked.

Yeah, CPU temperatures are provided by OHMJniWrapper.

How are you running the .bat file? Right-click and "Run as administrator"?

Can you try searching for cmd.exe in the start menu and then doing "Run as administrator" on that one.

Then cd to the directory with the bat file and then run it from there

Here's how in case you need it:

https://www.wikihow.com/Run-a-Batch-File-from-the-Command-Line-on-Windows

https://www.wikihow.com/Change-Directories-in-Command-Prompt

**Comment by colebolebole** [comment]
Thanks! I will try soon

**Comment by colebolebole** [comment]
just tried it, and it works even when i run it as admin, thank you for your help!
