### ISSUE TITLE
alpine liunx can not run

### ISSUE THREAD

**Issue by bestruirui** [Krillsson/sys-API#69]
![image](https://user-images.githubusercontent.com/89796393/184543921-0c85a786-5343-4d87-8b69-77d5338309b2.png)
WARN  [2022-08-14 23:20:19,471] org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable: HV000254: Missing parameter metadata for TimeUnit(String, int, long), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
WARN  [2022-08-14 23:20:19,590] org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable: HV000254: Missing parameter metadata for ChronoUnit(String, int, String, Duration), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
INFO  [2022-08-14 15:20:21,020] org.eclipse.jetty.util.log: Logging initialized @16012ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2022-08-14 15:20:21,559] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2022-08-14 15:20:21,574] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /admin
INFO  [2022-08-14 15:20:21,576] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: graphql-playground for path /*
WARN  [2022-08-14 15:20:27,047] graphql.kickstart.tools.SchemaClassScanner: Schema type was defined but can never be accessed, and can be safely deleted: NumericalValueMonitorType
WARN  [2022-08-14 15:20:27,047] graphql.kickstart.tools.SchemaClassScanner: Schema type was defined but can never be accessed, and can be safely deleted: FractionalValueMonitorType
WARN  [2022-08-14 15:20:27,047] graphql.kickstart.tools.SchemaClassScanner: Schema type was defined but can never be accessed, and can be safely deleted: ConditionalValueMonitorType
INFO  [2022-08-14 15:20:29,086] com.smoketurner.dropwizard.graphql.CachingPreparsedDocumentProvider: Query Cache: CacheBuilderSpec{maximumSize=10000}
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/monitee/server-shadow-0.17.1/lib/server-0.17.1-all.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.UnsatisfiedLinkError: Unable to load library 'udev':
Error loading shared library libudev.so: No such file or directory
Error loading shared library libudev.so: No such file or directory
Native library (linux-x86-64/libudev.so) not found in resource path (/monitee/server-shadow-0.17.1/lib/server-0.17.1-all.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Library$Handler.<init>(Library.java:192)
        at com.sun.jna.Native.load(Native.java:622)
        at com.sun.jna.Native.load(Native.java:596)
        at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
        at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:166)
        at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:82)
        at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:64)
        at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62)
        at oshi.util.Memoizer$1.get(Memoizer.java:87)
        at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68)
        at com.krillsson.sysapi.core.metrics.defaultimpl.DefaultMetricsFactory.create(DefaultMetricsFactory.kt:21)
        at com.krillsson.sysapi.core.metrics.MetricsFactory.createPlatformSpecific(MetricsFactory.kt:108)
        at com.krillsson.sysapi.core.metrics.MetricsFactory.get(MetricsFactory.kt:56)
        at com.krillsson.sysapi.SysAPIApplication.run(SysAPIApplication.kt:167)
        at com.krillsson.sysapi.SysAPIApplication.run(SysAPIApplication.kt:79)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.krillsson.sysapi.SysAPIApplication$Companion.main(SysAPIApplication.kt:302)
        at com.krillsson.sysapi.SysAPIApplication.main(SysAPIApplication.kt)
        Suppressed: java.lang.UnsatisfiedLinkError: Error loading shared library libudev.so: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 22 more
        Suppressed: java.lang.UnsatisfiedLinkError: Error loading shared library libudev.so: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
                ... 22 more
        Suppressed: java.io.IOException: Native library (linux-x86-64/libudev.so) not found in resource path (/monitee/server-shadow-0.17.1/lib/server-0.17.1-all.jar)
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
                ... 22 more

**Comment by Krillsson** [comment]
hi @bestruirui, you seem to run into the same issue as described here: https://github.com/oshi/oshi/issues/271

As udev.so seem to be available for alpine through this package: https://pkgs.alpinelinux.org/contents?branch=edge&name=eudev-dev&arch=x86_64&repo=main

could you please try that?

**Comment by Krillsson** [comment]
any update @bestruirui? Unless you need more assistance I will be closing this issue soon.

**Comment by Krillsson** [comment]
Closing due to inactivity...
