### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by zkvvoob** [Krillsson/sys-api#9]
Hello,

I'm trying to set up the sys-api in order to use it with your Monitee android app but when I test-run the server, I get the error below.

The machine is running Ubuntu 14.04 with 

    java version "1.8.0_161"
    Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
    Java HotSpot(TM) Server VM (build 25.161-b12, mixed mode)

Could you help me figure out what's wrong?

```INFO  [2018-02-03 17:38:50,016] org.eclipse.jetty.util.log: Logging initialized @4272ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2018-02-03 17:38:50,299] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /v1
INFO  [2018-02-03 17:38:50,308] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2018-02-03 17:38:51,862] io.dropwizard.server.ServerFactory: Starting System-Api


  ______ ______ ______ ______ ______ ______ ______
 |______|______|______|______|______|______|______|
 | |                                            | |
 | |    / ____|         | |                     | |
 | |   | (___  _   _ ___| |_ ___ _ __ ___       | |
 | |    \___ \| | | / __| __/ _ | '_ ` _ \      | |
 | |    ____) | |_| \__ | ||  __| | | | | |     | |
 | |   |_____/ \__, |___/\__\___|_| |_| |_|     | |
 | |            __/ |                           | |
 |_|           |___/__ _____                    |_|
 | |       /\   |  __ |_   _|                   | |
 | |      /  \  | |__) || |                     | |
 | |     / /\ \ |  ___/ | |                     | |
 | |    / ____ \| |    _| |_                    | |
 | |   /_/    \_|_|   |_____|                   | |
 | |                                            | |
 |_|____ ______ ______ ______ ______ ______ ____|_|
 |______|______|______|______|______|______|______|


INFO  [2018-02-03 17:38:52,151] org.eclipse.jetty.setuid.SetUIDListener: Opened application@dacf20{HTTP/1.1,[http/1.1]}{0.0.0.0:8069}
ERROR [2018-02-03 17:38:52,154] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.net.BindException: Address already in use
! at sun.nio.ch.Net.bind0(Native Method)
! at sun.nio.ch.Net.bind(Net.java:433)
! at sun.nio.ch.Net.bind(Net.java:425)
! at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
! at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
! at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:334)
! at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:302)
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200)
! ... 8 common frames omitted
! Causing: java.lang.RuntimeException: java.net.BindException: Address already in use
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:75)
! at io.dropwizard.Application.run(Application.java:93)
! at com.krillsson.sysapi.SystemApiApplication.main(SystemApiApplication.java:71)
java.lang.RuntimeException: java.net.BindException: Address already in use
        at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:213)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:93)
        at com.krillsson.sysapi.SystemApiApplication.main(SystemApiApplication.java:71)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:334)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:302)
        at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:200)
        ... 8 more
```

**Comment by Krillsson** [comment]
have you verified that the port is not already in use by another service?
Run this in a terminal:
`$ netstat -nap | grep 8069`
And then for the admin port (8070?)
`$ netstat -nap | grep 8070`
Either kill the service that is using the ports or configure another port for Sys-API.

**Comment by Krillsson** [comment]
You seem to have fixed your issue. I will close your issue now. If you need further help you can email via the support email from the play store.

**Comment by zkvvoob** [comment]
Hi Krillsson,

Sorry for not replying sooner. I ran the two commands and no service appeared to be listening on these ports.
